name: 'Topicus Forwarding Proxy for Github Actions'
description: 'Allow adding an (api token) header to requests'
inputs:
  api_key_header:
    description: 'The header name'
    required: true
  api_key_value:
    description: 'The header value'
    required: true
  proxy_to:
    description: 'Where to proxy to'
    required: true
  proxy_port:
    description: 'The port on localhost this proxy binds to'
    required: false
    default: 8080
runs:
  using: "composite"
  steps:
    - run: node $GITHUB_ACTION_PATH/dist/index.js &
      shell: bash
